version: '2'
volumes:
    resin-data:
    hass-config:
services:
    blinds:
        build: ./blinds
        privileged: true
        ports:
            - '8008:80'
            - '8080'
        volumes:
            - 'resin-data:/data'
    hass:
        build: ./hass
        cap_add:
            - NET_ADMIN
        restart: always
        network_mode: host
        volumes:
            - 'hass-config:/config'
    git:
        build: ./git
        restart: always
        volumes:
            - 'hass-config:/config'
